version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: yarn run start
    
